/**
 * Data registry - auto-generated by vidpilot skill.
 *
 * This file maps account IDs to their data modules.
 * The skill updates this file automatically when generating content.
 * You can also manually import your data files here.
 *
 * Usage: import data files for each account, then register them below.
 */

// ── Example account data (replace with your own) ─────────────
import { dialogue as exampleDialogue } from "./example/dialogue.example";
import { slides as exampleSlides, theme as exampleSlidesTheme } from "./example/slides.example";
import { rankSlides as exampleRankSlides, theme as exampleRankTheme } from "./example/ranking.example";
import { codeSteps as exampleCodeSteps, theme as exampleCodeTheme } from "./example/code.example";
import { segments as exampleSegments, theme as exampleNarrationTheme } from "./example/narration.example";

// ── Registry type ────────────────────────────────────────────
interface FormatData {
  data: any[];
  totalFrames: number;
  theme?: string;
}

export interface AccountDataRegistry {
  dialogue?: FormatData;
  slides?: FormatData;
  ranking?: FormatData;
  code?: FormatData;
  narration?: FormatData;
}

function sumFrames(items: { duration: number }[]): number {
  return items.reduce((s, l) => s + l.duration, 0);
}

// ── Register your accounts here ──────────────────────────────
// The skill auto-updates this section when generating content.
// Format: accountId -> { format -> { data, totalFrames, theme? } }

export const registry: Record<string, AccountDataRegistry> = {
  example: {
    dialogue: {
      data: exampleDialogue,
      totalFrames: sumFrames(exampleDialogue),
    },
    slides: {
      data: exampleSlides,
      totalFrames: sumFrames(exampleSlides),
      theme: exampleSlidesTheme,
    },
    ranking: {
      data: exampleRankSlides,
      totalFrames: sumFrames(exampleRankSlides),
      theme: exampleRankTheme,
    },
    code: {
      data: exampleCodeSteps,
      totalFrames: sumFrames(exampleCodeSteps),
      theme: exampleCodeTheme,
    },
    narration: {
      data: exampleSegments,
      totalFrames: sumFrames(exampleSegments),
      theme: exampleNarrationTheme,
    },
  },
};
