/**
 * Auto-generated by setup-accounts.mjs — DO NOT EDIT MANUALLY.
 * Static account config for Remotion (no fs dependency).
 */
import { AccountConfig } from "./types";

export const globalConfig = { fps: 30, width: 1080, height: 1920 };

export const accounts: Record<string, AccountConfig> = {
  "laodong": {
    id: "laodong",
    name: "程序员老东",
    outputDir: "output/laodong",
    leftCharacter: { name: "小李", image: "left.png", imageWidth: 533, imageHeight: 800, faceCenter: { x: 208, y: 280, radius: 160 } },
    rightCharacter: { name: "老王", image: "right.png", imageWidth: 676, imageHeight: 800, faceCenter: { x: 350, y: 250, radius: 130 } },
    backgroundImage: "bg.png",
    defaultTheme: "dark",
    voiceSeeds: { left: 42, right: 2024, narrator: 2024 },
    formats: ["dialogue","slides","ranking","code","narration","article"],
  },
  "stock": {
    id: "stock",
    name: "A股早知道",
    outputDir: "output/stock",
    leftCharacter: { name: "小韭", image: "left.png", imageWidth: 533, imageHeight: 800, faceCenter: { x: 208, y: 280, radius: 160 } },
    rightCharacter: { name: "老张", image: "right.png", imageWidth: 676, imageHeight: 800, faceCenter: { x: 350, y: 250, radius: 130 } },
    backgroundImage: "bg.png",
    defaultTheme: "warm",
    voiceSeeds: { left: 42, right: 2024, narrator: 2024 },
    formats: ["dialogue"],
  },
};

export function getAccount(id: string): AccountConfig {
  const account = accounts[id];
  if (!account) {
    throw new Error(`Unknown account: "${id}". Available: ${Object.keys(accounts).join(", ")}`);
  }
  return account;
}
